import type { Metadata } from "next";
import "../styles/globals.css";
import SessionProvider from "@/components/auth/SessionProvider";
import Toast from "@/components/Toast";

export const metadata: Metadata = {
  title: "Sobat Hukum",
  description: "Generated by create next app",
  keywords: ["hukum", "bantuan hukum", "masyarakat", "bantuan hukum masyarakat"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50">
        <SessionProvider>
          <Toast />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
